### PR TITLE
#38 support for hydrating/diluting/measuring concentrations of strands

### LINKED ISSUE #38: hydrate/dilute/measure concentrations of strands
Add some utility functions to `alhambra.mixes` that support the following workflow:

1. (Optional) Hydrate dry (lyophilized) DNA strand in buffer/water, to a desired concentration, based on reported nmoles of dry product.
2. Measure concentration of strand using UV260 absorbance (e.g., on a NanoDrop machine), based on extinction coefficient.
3. Dilute strand with a given concentration and volume to a target concentration.

Also provide support for "bulk" processing. For example, IDT gives an Excel data sheet giving nmoles and extinction coefficients of each strand; a function `hydrate_from_excel` should be able to read nmoles directly from there, and `measure_conc_from_excel` should be able to read extinction coefficients directly from there.

### PR DESCRIPTION
**Pull request by dave-doty**
Closes #38

### CODE REVIEW

**Comment by dave-doty** [comment]
Sorry, I don't understand the mypy error in the CI check, or how to fix it. It doesn't like me using `Q_` as a type in `alhambra.quantitate`, even though it's similar to what's happening in `alhambra.mixes`.

**Comment by cgevans** [comment]
> Sorry, I don't understand the mypy error in the CI check, or how to fix it. It doesn't like me using `Q_` as a type in `alhambra.quantitate`, even though it's similar to what's happening in `alhambra.mixes`.

`Quantity` and `Q_` are different in `alhambra.mixes`.  `Quantity` is the base type (`pint.Quantity`), while `Q_` creates a `Quantity` tied to a specific `UnitRegistry`.  `pint.Quantity[Decimal]` should be used for typing, while `alhambra.mixes.Q_` should be used to instantiate units.

**Comment by dave-doty** [comment]
@cgevans I'm pretty mystified by these mypy errors; nothing I try fixes them. It's not helping that I can't get my local mypy to produce any of them. (And it reports errors on the `match` statements even when I specify to only check Python version 3.10.) Maybe we can work through it in person on Monday.

**Comment by cgevans** [comment]
This should fix it.

**Review by cgevans — APPROVED** [review]

**Pull request merged**
